# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 23:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog_main', '0003_auto_20171201_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 1, 23, 16, 45, 261515, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 1, 23, 16, 45, 262016, tzinfo=utc)),
        ),
    ]
