# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 00:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog_main', '0004_auto_20171201_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 2, 0, 17, 7, 898151, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 2, 0, 17, 7, 898653, tzinfo=utc)),
        ),
    ]
